### PR TITLE
Feature: get status of all jobs

### PR DESCRIPTION
**Pull request by johandahlberg**
I added a small feature to get the status of all currently running jobs.

I also:
 - did some refactoring of the tests
 - pulled out `Status` from job into it's own class to make it easier to reuse.
 - fixed a bug (or at least a deviation for the doc) for `stop_jobs_with_id`

I'm still very much a beginner in python so any feedback would be very welcome.

### CODE REVIEW

**Comment by johandahlberg** [comment]
I'm not 100% sure about 7488217, but when I try to use localq as a library and create a job through it I can't seem to get it to work unless `shell=True`. What do you think about that?

**Comment by dakl** [comment]
Thanks @johandahlberg - looks great! 

`shell=True` shouldn't be needed. I've had success using it without it using `lbatch` to submit the jobs (which calls `LocalQServer`'s `add`).

How are you submitting the jobs? Unfortunately I won't have access to do proper tests myself until I'm back at work on Aug 10. 

(side note: `lbatch` should probably be renamed `lrun` at some point or similar since it can take any executable command (rather than just a script as `sbatch`)). 

Apart from the `shell=True` part, everything looks swell. I think the easiest thing would be to remove it from this PR, and investigate separately.

**Comment by johandahlberg** [comment]
I've now updated and removed the `shell=True` part.

I'm using lqueue in a small webservice I'm working on to start `bcl2fastq` over here at the platform. Can't give you a url just yet since I haven't pushed it to github. The idea is to use lqueue to manage so that to many jobs do not get started at once.

**Comment by johandahlberg** [comment]
Also, let me know if you want me to rebase this PR to give you a cleaner history to merge.

**Comment by johandahlberg** [comment]
Thanks for the merge! I still have the problem with not getting my program to run without setting `shell=True` however. I can probably create a real example of this for you, and maybe you could comment on if you have any ideas on why that might be the case?

**Comment by dakl** [comment]
A real example would be great. What python version are you using?

**Comment by johandahlberg** [comment]
I'm using python 2.7. This is a minimal example that recreates the problem:

```
import sys
import time

from localq.LocalQServer import LocalQServer

def main():

    server = LocalQServer(num_cores_available=2, interval=1, priority_method="fifo")
    server.run()
    job_id = server.add("ls -l", 1, "/tmp")
    time.sleep(2)
    result = server.get_status(job_id)
    print result


if __name__ == "__main__":
    sys.exit(main())
```

If I set `shell=True` in the Job-class this works - if not I get `FAILED` back. Any ideas?

**Comment by dakl** [comment]
Ah - now I see the problem. 

The `cmd` parameter has to be an array of the components of the command line. Changing the job to 

```
    job_id = server.add(["ls", "-l"], 1, "/tmp")
```

gives

```
$ python lqtest.py 
Starting localqd with 2 available cores
Checking queue every 1.0 seconds
COMPLETED
```

The reason for this is security. Blindly allowing spaces or pipes (including `;` and `|` which is what `shell=True` does) is a risk. This stops users from injecting stuff like `; rm -rf $HOME` in parameters (see https://docs.python.org/2/library/subprocess.html#frequently-used-arguments for more).

**Comment by johandahlberg** [comment]
I can confirm that it's working if the command is feed as an array.

H for the use-case of a localq I'm wondering if this is actually a problem. Since the user could execute the same command anyway by simply submitting it to the job-queue. E.g. `server.add(["rm", "-rf", "/home/*"], 1, "/tmp")` would still allow the user to wreck havoc everywhere the user has permissions?

**Comment by dakl** [comment]
Yes it would. But the common scenario (or rather reason for discouraging `shell=True`) is rather that the end user can set parameters in predefined tools. An example would be a user-expose tool called `listFiles`, with a single settable parameter `dir` to create a `cmd` of ["ls", "-l", dir]. In this scenario, using `shell=True` allows a user to set `dir="$HOME; rm -rf $HOME"`. 

Now imagine that the tools are exposed as a web service where the user running the tool isn't logged in to the server itself, but just passes in parameters and gets results back. Any user of the web frontend could then delete or create files arbitrarily on the service's account on the server. 

Anyway - that's the theory. In this case, a user adding jobs programmatically can of course do whatever the underlying permissions allow...

**Comment by dakl** [comment]
Adding `shell=True` would make it possible to write command lines more easily using for example 

```
from string import Template
s = Template('samtools view ${file} | head -n 100')
cmd = s.substitute(file="myfile.bam")
print cmd
```

That's way easier to debug than `['samtools', 'view', ...]`. Also, the current implementation would not allow the pipes to be there.

**Comment by johandahlberg** [comment]
I'm 100% on-board why this is a bad thing in e.g. a publically exposed webservice. However for this localq I'd like to argue that being able to use the shell, with examples such as yours above would be a nice feature. How would you feel about making in a option that is `False` by default? That way folks (such as myself) who use localq as a library in their applications have the option to pick that they think fits their use-case best?

**Comment by dakl** [comment]
I just fixed this in 0.1.6. There's now a parameter `use_shell=True` when creating a server. 

```python
import sys
import time

from localq.LocalQServer import LocalQServer

def main():

    server = LocalQServer(num_cores_available=2, interval=1, priority_method="fifo", use_shell=True)
    server.run()
    job_id = server.add("ls -l", 1, "/tmp")
    time.sleep(2)
    result = server.get_status(job_id)
    print result


if __name__ == "__main__":
    sys.exit(main())
```
 now prints `COMPLETED`.

**Comment by johandahlberg** [comment]
Awesome!

**Pull request merged**
